services:
    bitbag.sem_tools_plugin.feed_parser.google:
        class: BitBag\SEMToolsPlugin\FeedParser\GoogleFeedParser
        arguments:
            - '@bitbag.sem_tools_plugin.feed_parser.helper'

    bitbag.sem_tools_plugin.feed_parser.facebook:
        class: BitBag\SEMToolsPlugin\FeedParser\FacebookFeedParser
        arguments:
            - '@bitbag.sem_tools_plugin.feed_parser.helper'

    bitbag.sem_tools_plugin.feed_parser.helper:
        class: BitBag\SEMToolsPlugin\FeedParser\FeedParserHelper
        arguments:
            - '@router'
            - '@sylius.availability_checker.default'
            - '@sylius.calculator.product_variant_price'
            - '@sylius.context.channel'
            - '@sylius.context.currency'